### ISSUE TITLE
News Page Media Query Bug

### ISSUE THREAD

**Issue by MathyouMB** [CarletonComputerScienceSociety/website#101]
Can we make it break into mobile sooner?

<img width="169" alt="Screenshot 2021-07-13 at 2 49 04 PM" src="https://user-images.githubusercontent.com/43223682/125508418-ebe4f275-a708-42ab-bd79-567008daee08.png">

**Comment by EliasJRH** [comment]
What width was this on?

**Comment by MathyouMB** [comment]
this is what I got it on

![image](https://user-images.githubusercontent.com/43223682/125641558-7c7d7686-5c61-43f7-bdf1-69454e5dbe82.png)
