### ISSUE TITLE
Event Card "Gray line" bug

### ISSUE THREAD

**Issue by MathyouMB** [CarletonComputerScienceSociety/website#176]
There seems to be a 1 pixel gray line at the bottom of mobile event posters. Please update the CSS to fix this.

<img width="726" alt="Screenshot 2021-09-23 at 2 33 22 PM" src="https://user-images.githubusercontent.com/43223682/134564073-aacebe60-69f9-4de4-93ee-ff64834d6fc1.png">

**Comment by anasilveira9787** [comment]
Hello! Can I help to fix it? I need one more PR approval to count for Hacktoberfest. Thanks!
