### ISSUE TITLE
Navbar "1 pixel" border gap

### ISSUE THREAD

**Issue by MathyouMB** [CarletonComputerScienceSociety/website#212]
On the Mac version of chrome, seems to be a very slight gap between the black background of the navbar and the red border at the bottom of the navbar.

--

<img width="1439" alt="Screenshot 2022-06-01 at 11 22 40 PM" src="https://user-images.githubusercontent.com/43223682/171546598-0c76ae12-d1a1-4f81-9f96-7e5328fcd677.png">

--

<img width="155" alt="Screenshot 2022-06-01 at 11 25 18 PM" src="https://user-images.githubusercontent.com/43223682/171546663-2ef4c03e-d14e-4a60-b92c-6f7535558035.png">

**Comment by RohanSreelesh** [comment]
replicated on chrome Version 102.0.5005.63 (Official Build) (64-bit)


![Image](https://user-images.githubusercontent.com/31416057/171745744-081b31a5-0fe1-468f-bd41-cfbef4d666fe.png)




![Image](https://user-images.githubusercontent.com/31416057/171745760-82ed7db8-c47e-4396-bfc7-8844c490a8c7.png)
