### ISSUE TITLE
Article Component Background is not white

### ISSUE THREAD

**Issue by MathyouMB** [CarletonComputerScienceSociety/website#248]
Please update the background color of these components to be pure white and not this "almost white" color.

You can see on the right side where the text is that the background color isn't actually white, it's "off white" or something.
![Image](https://user-images.githubusercontent.com/43223682/188017831-8afa7cf8-6c56-422f-86b1-55367eb31b2d.png)

https://ccss.carleton.ca/news/

**Comment by ryangchung** [comment]
Hey @Nguyen-HanhNong!

Since this issue hasn't been resolved, I'm going to be leaving it open to any contributor. Feel free to reassign yourself if you would still like to complete it.

**Comment by nhannhuthung** [comment]
I want to contribute this change

**Comment by cpz98** [comment]
I would like to contribute to this
