### ISSUE TITLE
Blog post headers all same size

### ISSUE THREAD

**Issue by AngelOnFira** [CarletonComputerScienceSociety/website#260]
In blog posts, header 1 `#` and header 2 `##` are the same size. It would be helpful if they were different to distinguish sections better.

The markdown below:

```markdown
# Challenges

## Treasure Hunt

...

### 1. A Wall of CPUs (Herzburg)

### 2. The Hall Behind Tims (UC)
```

Is rendered as follows ([website view](https://ccss.carleton.ca/blog/2022-2023/2022-06-20-ccss-summer-dev-projects-introduction-copy/)):

![image](https://user-images.githubusercontent.com/14791619/191549475-67e3f7ab-3978-4ff9-a67f-05895ddb0962.png)

**Comment by leroialfonse** [comment]
Hi, can I be assigned to this task?

**Comment by AngelOnFira** [comment]
Sure! Feel free to give it a go :)
