### ISSUE TITLE
Change Discord link

### ISSUE THREAD

**Issue by AngelOnFira** [CarletonComputerScienceSociety/website#263]
Can we change this image to a link in the repo? It's not loading for me in Firefox, I assume since Discord is probably doing more rate limiting for browsers now.

https://github.com/CarletonComputerScienceSociety/website/blob/042dae1aab9100b3f882e4287255019205a095ed/assets/scss/components/_header.scss#L5

**Comment by nhannhuthung** [comment]
I want to contribute this change.
