### ISSUE TITLE
Adjust home page initiatives

### ISSUE THREAD

**Issue by MathyouMB** [CarletonComputerScienceSociety/website#347]
For this issue, we will be updating this section on the home page:

![Image](https://github.com/CarletonComputerScienceSociety/website/assets/43223682/25aa0e80-3a07-4abf-81b2-7e297e41ab60)

You will need to edit the following file: `data/initiatives.yml`

I'd like it if we replaced "carleton merged" with "CCSS Resources" and linked out to https://resources.carletoncomputerscience.ca/

I'd like us to also change the order of the initiatives to in the following order:

- CCSS Resources
- DiscreteMath.ca
- CCSS Magazine

**Comment by oceansync** [comment]
I can take this
