### ISSUE TITLE
Utilize Hugo Dates for footer

### ISSUE THREAD

**Issue by MathyouMB** [CarletonComputerScienceSociety/website#349]
In the footer, we currently use JS to determine the "year" to display in our footer copyright section:

![Image](https://github.com/CarletonComputerScienceSociety/website/assets/43223682/baa03184-f5e6-43c6-a4d2-619623f661d0)

Checkout the following file `layouts/partials/footer.html`

Instead of using js, we should really be using Hugo dates to determine the curent year.

Here is a "help forum" where someone asked how this can be done: https://discourse.gohugo.io/t/how-do-i-display-the-current-year/1174

It appears we should be able to use this code snippet `{{ .Now.Year }}`

**Comment by oceansync** [comment]
I will take this
