### ISSUE TITLE
Remove / Fix Shynet Error

### ISSUE THREAD

**Issue by MathyouMB** [CarletonComputerScienceSociety/website#350]
The following error currently occurs: 

![Image](https://github.com/CarletonComputerScienceSociety/website/assets/43223682/7d28f6ef-959c-41e1-9b6d-f0c471fd2bbd)

This shynet error occurs because our telemetry service is currently down. 

This error impacts our SEO score, so it's best we comment out the shynet code here: `layouts/_default/baseof.html` or fix shynet as a whole (which will require Forest's help).

**Comment by eros-mcguire** [comment]
Shynet has sent the terminator. I will terminate Shynet
