### ISSUE TITLE
Update CuHacking info on Organizations Page

### ISSUE THREAD

**Issue by MathyouMB** [CarletonComputerScienceSociety/website#351]
![Image](https://github.com/CarletonComputerScienceSociety/website/assets/43223682/be5d2c21-4347-4859-bc55-9c0f97d793dd)

The link, logo, and description of CuHacking are outdated.  This info can be updated here: `data/organizations.yml`

Here is the new link: https://www.cuhacking.ca/

I do not off hand have an improved logo image, so feel free to crop the one they have on their website and or get a picture via their discord.

**Comment by djoga24** [comment]
I would like to work on this!

**Comment by djoga24** [comment]
Completed
