### ISSUE TITLE
Update WICS info on Organizations Page

### ISSUE THREAD

**Issue by MathyouMB** [CarletonComputerScienceSociety/website#352]
Checkout [https://ccss.carleton.ca/community/organizations/](https://ccss.carleton.ca/community/organizations/)

The link for WICS is broken.  This info can be updated here: `data/organizations.yml`

I wasn't able to find a new link, so potentially inquire in their discord and if there isn't a working site, link to their instagram instead.

**Comment by yufengliu15** [comment]
i can work on this one
