### ISSUE TITLE
Add missing 2023-2024 Talks

### ISSUE THREAD

**Issue by MathyouMB** [CarletonComputerScienceSociety/website#357]
We have a page on our website: https://ccss.carleton.ca/events/talks/ which features all "talk" related events.

![Image](https://github.com/CarletonComputerScienceSociety/website/assets/43223682/897c40a1-8d3d-455e-a4eb-a8c87a05c9ab)

This page is generated by finding all events with the "talks" tag.

We have not done a good job of tagging events with the "talks" tag so far in the 2023-2024 year. For this issue, please add any 2023-2024 talk events to the talks page by giving them the talks tag.

**Comment by djoga24** [comment]
I would like to work on this

**Comment by djoga24** [comment]
I am done
