### ISSUE TITLE
Footer Improvements

### ISSUE THREAD

**Issue by MathyouMB** [CarletonComputerScienceSociety/website#358]
The footer on our old website featured important info like our email, address, etc. Check it out here: https://carletoncomputersciencesociety.github.io/

We should add this stuff to the current footer.

![Image](https://github.com/CarletonComputerScienceSociety/website/assets/43223682/01dcb822-5220-4629-9b13-6bdd8c32e715)

**Comment by B2015018** [comment]
Hi there. Can you assign me

**Comment by marceljc3** [comment]
a
