### ISSUE TITLE
Add Discord link to mobile header

### ISSUE THREAD

**Issue by MathyouMB** [CarletonComputerScienceSociety/website#361]
Today on mobile when you click the "discord" button on mobile, nothing happens. This is because there isn't actually a link there... I somehow forgot to add this...

Checkout: `layouts/partials/header.html` to add the link.

![Image](https://github.com/CarletonComputerScienceSociety/website/assets/43223682/b75bf04a-d440-4233-aa62-96fe16a8e3d9)

**Comment by eros-mcguire** [comment]
hello
