### ISSUE TITLE
"Example Site" on PRs Github Action Spike

### ISSUE THREAD

**Issue by MathyouMB** [CarletonComputerScienceSociety/website#363]
It would be really awesome if on prs, we had a Github action that created a "preview" version of the site so that the reviewer doesnt need to checkout the code each time.

Here is an example of what netlify provides: 

![Image](https://user-images.githubusercontent.com/8465237/50720388-6f3f8880-107a-11e9-8717-dfd2bedd7c07.png)

Please research and prototype setting this up on the website repository.

**Comment by yufengliu15** [comment]
i'm interested in trying this out, if anyone wants to help feel free.

**Comment by yufengliu15** [comment]
https://gohugo.io/hosting-and-deployment/hosting-on-github/

This looks like a very good website to implement this feature

**Comment by MathyouMB** [comment]
Bug finally resolved in https://github.com/CarletonComputerScienceSociety/website/pull/390
