### ISSUE TITLE
Update Lounge Notice on Home Page

### ISSUE THREAD

**Issue by ryangchung** [CarletonComputerScienceSociety/website#420]
The lounge notice at https://ccss.carleton.ca/ is over a year outdated (see image below), and can be updated with the following text: "The CCSS lounge and all in-person services are available at Herzberg Laboratories in room 4135, near the Teaching Assistant (TA) Center!"

![image](https://github.com/CarletonComputerScienceSociety/website/assets/87027981/729db36e-435b-471d-b27c-4868057ef0e7)

**Comment by Dhruvekariya** [comment]
hey, i would like contribute to this changes

**Comment by ryangchung** [comment]
> hey, i would like contribute to this changes

Sounds good, you've been assigned!

**Comment by ryangchung** [comment]
> hey, i would like contribute to this changes

Hi, unfortunately these issues are for an event we're running for Carleton University students.

**Comment by nhannhuthung** [comment]
I want to contribute to this change
