### ISSUE TITLE
Fix Alignment of Header Links

### ISSUE THREAD

**Issue by ryangchung** [CarletonComputerScienceSociety/website#421]
The alignment of the header links icon on the home page https://ccss.carleton.ca/ is off:
![image](https://github.com/CarletonComputerScienceSociety/website/assets/87027981/b18327b3-7c89-4b2a-aacf-29c1953abfe4)

This is the intended alignment (or something similar, where the icon starts at the bottom of most regular characters:
![image](https://github.com/CarletonComputerScienceSociety/website/assets/87027981/1af45373-d520-4e79-8d8a-edbb991d766e)

The changes should reflect on all header links (Spotlight, Featured Events, Initiatives). This can be done with only CSS.

**Comment by ParamDesai111** [comment]
I would like to contribute to this one!
