### ISSUE TITLE
Move Pages from Blog to News

### ISSUE THREAD

**Issue by ryangchung** [CarletonComputerScienceSociety/website#422]
The following 4 posts in https://ccss.carleton.ca/blog/ (can be better seen in an itemized list in https://ccss.carleton.ca/blog/archive/) are not blogs, so they should be moved into the news section:

![image](https://github.com/CarletonComputerScienceSociety/website/assets/87027981/5b4fd0e8-12ec-4b95-be0e-a051e5ebd160)

**Comment by fatemalokhand** [comment]
I would like to do this
