### ISSUE TITLE
Discord Home Page Spacing

### ISSUE THREAD

**Issue by MathyouMB** [CarletonComputerScienceSociety/website#49]
Spacing on the icon next to discord looks a little too small on some browsers

![image](https://user-images.githubusercontent.com/43223682/124498004-b3b25900-dd89-11eb-923b-637261bda4c5.png)

**Comment by EliasJRH** [comment]
The spacing seems to be consistent on Firefox, Chrome and Edge. Which browser was this found on?

**Comment by MathyouMB** [comment]
The chrome on my laptop looks fine, but on the chrome on my desktop, I found it seemed to close to the word discord
