### ISSUE TITLE
Event Card and "Featured Article" red notch white space bug

### ISSUE THREAD

**Issue by MathyouMB** [CarletonComputerScienceSociety/website#54]
On certain browsers, if you zoom in on the notch on event cards and the "featured article" you can see a white line inside the notch

![image](https://user-images.githubusercontent.com/43223682/124630044-06eedf00-de50-11eb-848b-a51427180a6e.png)

**Comment by EliasJRH** [comment]
Note: Only seems to be an issue on chromium-based(ish) browsers like chrome and edge

**Comment by MathyouMB** [comment]
Yeah I've only gotten it on my desktop chrome.

**Comment by MathyouMB** [comment]
Adding this for more obvious visual 

<img width="137" alt="Screenshot 2021-09-23 at 2 39 21 PM" src="https://user-images.githubusercontent.com/43223682/134564900-2fe12f61-6ba0-4c37-bc8e-30f2b53f44f4.png">
