### ISSUE TITLE
"Organization" Card Component

### ISSUE THREAD

**Issue by MathyouMB** [CarletonComputerScienceSociety/website#56]
I'd like to have a component similar to event card for organizations. The only main difference will be that these cards have symbols which will link to their social media.

We should probably put this data on a yaml in the data folder and use templating to conditionally render certain social media symbols based on the provided data.

To get the social media symbols, use font-awesome icons. There are already a few font-awesome icons used in the app, one of them is next to the word "Discord" in the home page header.

Don't worry about making this as responsive as event cards. We can make these responsive later, for the MVP of this website we just need the normal square card.

Hopefully these designs wont look as ugly with only a few symbols instead of like 6...

![image](https://user-images.githubusercontent.com/43223682/124633586-67cbe680-de53-11eb-8e55-a0089de34e97.png)
![example](https://user-images.githubusercontent.com/43223682/124633613-71ede500-de53-11eb-9be8-007e25e5966b.png)

**Comment by EliasJRH** [comment]
Conditional check on yaml for hugo:
https://gohugo.io/functions/isset/
