### ISSUE TITLE
Organization Card Width Bug

### ISSUE THREAD

**Issue by MathyouMB** [CarletonComputerScienceSociety/website#68]
If an org's title is too long it increases the whole cards width instead of just doing an ellipsis.

<img width="735" alt="Screenshot 2021-07-07 at 1 35 01 PM" src="https://user-images.githubusercontent.com/43223682/124804458-5274bc00-df28-11eb-99cd-cae4c7ac1bb2.png">

**Comment by EliasJRH** [comment]
Should we just shorten the name of the organization if this is the case? As well, we could have the link to their website be accessible by clicking the name as well
